{
	"vulinfoid": "JVNDB-2024-002414",
	"vulinfodata": {
		"title": "vyperlang の Python 用 vyper におけるバッファエラーの脆弱性",
		"vulinfodescription": {
			"overview": "vyperlang の Python 用 vyper には、バッファエラーの脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "vyperlang",
					"productname": "vyper",
					"cpe": {
						"text": "cpe:/a:vyperlang:vyper",
						"version": "2.2"
					},
					"versionnumber": [
						"0.3.10 およびそれ以前"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "3.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "5.3",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
				}
			],
			"impactitem": {
				"description": "情報を取得される可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダアドバイザリまたはパッチ情報が公開されています。参考情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2024-24560",
					"url": "https://www.cve.org/CVERecord?id=CVE-2024-24560"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2024-24560",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-24560"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "github.com (GHSA-gp3w-2v2m-p686)",
					"url": "https://github.com/vyperlang/vyper/security/advisories/GHSA-gp3w-2v2m-p686"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-119",
					"url": "https://jvndb.jvn.jp/ja/cwe/CWE-119.html",
					"title": "バッファエラー"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2024-02-14T13:51:39+09:00",
					"description": "[2024年02月14日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2024-02-14T13:51:39+09:00",
		"datelastupdated": "2024-02-14T13:51:39+09:00",
		"datepublic": "2024-02-02T00:00:00+09:00"
	}
}
