{
  "vulinfoid": "JVNDB-2018-010974",
  "vulinfodata": {
    "title": "389 Directory Server におけるリソース管理に関する脆弱性",
    "vulinfodescription": {
      "overview": "389 Directory Server には、リソース管理に関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Debian",
          "productname": "Debian GNU/Linux",
          "cpe": {
            "text": "cpe:/o:debian:debian_linux",
            "version": "2.2"
          }
        },
        {
          "name": "Fedora Project",
          "productname": "389 Directory Server",
          "cpe": {
            "text": "cpe:/a:fedoraproject:389_directory_server",
            "version": "2.2"
          }
        },
        {
          "name": "レッドハット",
          "productname": "Red Hat Enterprise Linux",
          "cpe": {
            "text": "cpe:/o:redhat:enterprise_linux",
            "version": "2.2"
          }
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "High",
            "type": "Base"
          },
          "base": "7.8",
          "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:C"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "High",
            "type": "Base"
          },
          "base": "7.5",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "impactitem": {
        "description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダ情報および参考情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "389 Directory Server",
          "vulinfoid": "Top Page",
          "url": "https://directory.fedoraproject.org/"
        },
        {
          "type": "vendor",
          "name": "Debian",
          "vulinfoid": "[SECURITY] [DLA 1554-1] 389-ds-base security update",
          "url": "https://lists.debian.org/debian-lts-announce/2018/10/msg00015.html"
        },
        {
          "type": "vendor",
          "name": "Red Hat Bugzilla",
          "vulinfoid": "Bug 1630668",
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14648"
        },
        {
          "type": "vendor",
          "name": "Red Hat Security Advisory",
          "vulinfoid": "RHSA-2018:3127",
          "url": "https://access.redhat.com/errata/RHSA-2018:3127"
        },
        {
          "type": "vendor",
          "name": "Red Hat Security Advisory",
          "vulinfoid": "RHSA-2018:3507",
          "url": "https://access.redhat.com/errata/RHSA-2018:3507"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2018-14648",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-14648"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2018-14648",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-14648"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-399",
          "url": "https://jvndb.jvn.jp/ja/cwe/CWE-399.html",
          "title": "リソース管理の問題"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2018-12-28T14:33:39+09:00",
          "description": "[2018年12月28日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2018-12-28T14:33:39+09:00",
    "datelastupdated": "2018-12-28T14:33:39+09:00",
    "datepublic": "2018-10-30T00:00:00+09:00"
  }
}
