{
	"vulinfoid": "JVNDB-2019-014366",
	"vulinfodata": {
		"title": "samba における境界外読み取りに関する脆弱性",
		"vulinfodescription": {
			"overview": "samba には、境界外読み取りに関する脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "Canonical",
					"productname": "Ubuntu",
					"cpe": {
						"text": "cpe:/o:canonical:ubuntu_linux",
						"version": "2.2"
					}
				},
				{
					"name": "Samba Project",
					"productname": "Samba",
					"cpe": {
						"text": "cpe:/a:samba:samba",
						"version": "2.2"
					},
					"versionnumber": [
						"4.10.12 未満の 4.10.x",
						"4.11.5 未満の 4.11.x",
						"4.9.18 未満の 4.9.x"
					]
				},
				{
					"name": "Synology Inc.",
					"productname": "DiskStation Manager",
					"cpe": {
						"text": "cpe:/a:synology:diskstation_manager",
						"version": "2.2"
					}
				},
				{
					"name": "Synology Inc.",
					"productname": "Router Manager",
					"cpe": {
						"text": "cpe:/a:synology:router_manager",
						"version": "2.2"
					}
				},
				{
					"name": "Synology Inc.",
					"productname": "SkyNAS",
					"cpe": {
						"text": "cpe:/a:synology:skynas",
						"version": "2.2"
					}
				},
				{
					"name": "Synology Inc.",
					"productname": "Synology Directory Server",
					"cpe": {
						"text": "cpe:/a:synology:directory_server",
						"version": "2.2"
					}
				},
				{
					"name": "レッドハット",
					"productname": "Red Hat Enterprise Linux",
					"cpe": {
						"text": "cpe:/o:redhat:enterprise_linux",
						"version": "2.2"
					}
				},
				{
					"name": "レッドハット",
					"productname": "Red Hat Storage",
					"cpe": {
						"text": "cpe:/a:redhat:storage",
						"version": "2.2"
					}
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "2.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "4.3",
					"vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
				},
				{
					"version": "3.0",
					"severity": {
						"text": "High",
						"type": "Base"
					},
					"base": "7.5",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"impactitem": {
				"description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "vendor",
					"name": "Red Hat Security Advisory",
					"vulinfoid": "Bug 1791207",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14907"
				},
				{
					"type": "vendor",
					"name": "Samba Security Announcement",
					"vulinfoid": "Crash after failed character conversion at log level 3 or above",
					"url": "https://www.samba.org/samba/security/CVE-2019-14907.html"
				},
				{
					"type": "vendor",
					"name": "Synology Product Security Advisory",
					"vulinfoid": "Synology-SA-20:01",
					"url": "https://www.synology.com/security/advisory/Synology_SA_20_01"
				},
				{
					"type": "vendor",
					"name": "Ubuntu Security Notice",
					"vulinfoid": "USN-4244-1",
					"url": "https://usn.ubuntu.com/4244-1/"
				},
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2019-14907",
					"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14907"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2019-14907",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14907"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-125",
					"url": "https://cwe.mitre.org/data/definitions/125.html",
					"title": "境界外読み取り"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2020-02-12T15:48:33+09:00",
					"description": "[2020年02月12日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2020-02-12T15:48:33+09:00",
		"datelastupdated": "2020-02-12T15:48:33+09:00",
		"datepublic": "2019-08-10T00:00:00+09:00"
	}
}
