{
  "vulinfoid": "JVNDB-2010-002727",
  "vulinfodata": {
    "title": "Python の audioop モジュールにおけるサービス運用妨害 (DoS) の脆弱性",
    "vulinfodescription": {
      "overview": "Python の audioop モジュールは、size 引数と文字列のバイト長の関連性を検証しないため、サービス運用妨害 (DoS) 状態となる脆弱性が存在します。 本脆弱性は、CVE-2010-1634 とは異なる脆弱性です。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Python Software Foundation",
          "productname": "Python",
          "cpe": {
            "text": "cpe:/a:python:python",
            "version": "2.2"
          },
          "versionnumber": [
            "2.5.6c 未満",
            "2.6",
            "2.7",
            "3.1",
            "3.2"
          ]
        },
        {
          "name": "VMware",
          "productname": "VMware ESXi",
          "cpe": {
            "text": "cpe:/a:vmware:esxi",
            "version": "2.2"
          },
          "versionnumber": [
            "3.5",
            "4.0",
            "4.1",
            "5.0"
          ]
        },
        {
          "name": "サイバートラスト株式会社",
          "productname": "Asianux Server",
          "cpe": {
            "text": "cpe:/o:misc:miraclelinux_asianux_server",
            "version": "2.2"
          },
          "versionnumber": [
            "3 (x86) ",
            "3 (x86-64) ",
            "3.0 ",
            "3.0 (x86-64) ",
            "4.0 ",
            "4.0 (x86-64) "
          ]
        },
        {
          "name": "レッドハット",
          "productname": "Red Hat Enterprise Linux",
          "cpe": {
            "text": "cpe:/o:redhat:enterprise_linux",
            "version": "2.2"
          },
          "versionnumber": [
            "4 (as) ",
            "4 (es) ",
            "4 (ws) ",
            "4.8 (as) ",
            "4.8 (es) ",
            "5 (server) "
          ]
        },
        {
          "name": "レッドハット",
          "productname": "Red Hat Enterprise Linux Desktop",
          "cpe": {
            "text": "cpe:/o:redhat:enterprise_linux_desktop",
            "version": "2.2"
          },
          "versionnumber": [
            "4.0 ",
            "5.0 (client) "
          ]
        },
        {
          "name": "レッドハット",
          "productname": "RHEL Desktop Workstation",
          "cpe": {
            "text": "cpe:/o:redhat:rhel_desktop_workstation",
            "version": "2.2"
          },
          "versionnumber": [
            "5 (client) "
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "5",
          "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
        }
      ],
      "impactitem": {
        "description": "攻撃者により、巧妙に細工された引数を介して、サービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "Asianux Technical Support Network",
          "vulinfoid": "python-2.4.3-43.0.1.AXS3",
          "url": "https://tsn.miraclelinux.com/tsn_local/index.php?m=errata&a=detail&eid=1335"
        },
        {
          "type": "vendor",
          "name": "MIRACLE LINUX アップデート情報",
          "vulinfoid": "2219",
          "url": "https://www.miraclelinux.com/support/index.php?q=node/99&errata_id=2219"
        },
        {
          "type": "vendor",
          "name": "MIRACLE LINUX アップデート情報",
          "vulinfoid": "2221",
          "url": "https://www.miraclelinux.com/support/index.php?q=node/99&errata_id=2221"
        },
        {
          "type": "vendor",
          "name": "Python",
          "vulinfoid": "issue7673",
          "url": "http://bugs.python.org/issue7673"
        },
        {
          "type": "vendor",
          "name": "Python",
          "vulinfoid": "What's New in Python 2.5.6c1?",
          "url": "http://www.python.org/download/releases/2.5.6/NEWS.txt"
        },
        {
          "type": "vendor",
          "name": "Python",
          "vulinfoid": "releases",
          "url": "http://www.python.org/download/releases"
        },
        {
          "type": "vendor",
          "name": "Red Hat Security Advisory",
          "vulinfoid": "RHSA-2011:0491",
          "url": "https://rhn.redhat.com/errata/RHSA-2011-0491.html"
        },
        {
          "type": "vendor",
          "name": "Red Hat Security Advisory",
          "vulinfoid": "RHSA-2011:0027",
          "url": "https://rhn.redhat.com/errata/RHSA-2011-0027.html"
        },
        {
          "type": "vendor",
          "name": "VMware Security Advisories",
          "vulinfoid": "VMSA-2012-0001",
          "url": "http://www.vmware.com/jp/support/support-resources/advisories/VMSA-2012-0001.html"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2010-2089",
          "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-2089"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2010-2089",
          "url": "http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2010-2089"
        },
        {
          "type": "advisory",
          "name": "Secunia Advisory",
          "vulinfoid": "SA40148",
          "url": "http://secunia.com/advisories/40148"
        },
        {
          "type": "advisory",
          "name": "Secunia Advisory",
          "vulinfoid": "SA42888",
          "url": "http://secunia.com/advisories/42888"
        },
        {
          "type": "advisory",
          "name": "SecurityFocus",
          "vulinfoid": "40863",
          "url": "http://www.securityfocus.com/bid/40863"
        },
        {
          "type": "advisory",
          "name": "VUPEN Security",
          "vulinfoid": "VUPEN/ADV-2011-0122",
          "url": "http://www.vupen.com/english/advisories/2011/0122"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-119",
          "url": "https://jvndb.jvn.jp/ja/cwe/CWE-119.html",
          "title": "バッファエラー"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "0",
          "datetime": "2018-02-17T10:37:52+09:00",
          "description": "[2011年02月04日]\\n  掲載\\n[2011年05月20日]\\n  影響を受けるシステム：レッドハット (RHSA-2011:0491) の情報を追加\\n  ベンダ情報：レッドハット (RHSA-2011:0491) を追加\\n[2011年06月01日]\\n  影響を受けるシステム：Python Software Foundation (What's New in Python 2.5.6c1?) の情報を追加\\n  ベンダ情報：Python Software Foundation (What's New in Python 2.5.6c1?) を追加\\n[2011年06月07日]\\n  影響を受けるシステム：ミラクル・リナックス (2219) の情報を追加\\n  影響を受けるシステム：ミラクル・リナックス (2221) の情報を追加\\n  ベンダ情報：ミラクル・リナックス (2219) を追加\\n  ベンダ情報：ミラクル・リナックス (2221) を追加\\n[2012年12月18日]\\n  影響を受けるシステム：VMware (VMSA-2012-0001) の情報を追加\\n  ベンダ情報：VMware (VMSA-2012-0001) を追加"
        }
      ]
    },
    "datefirstpublished": "2011-02-04T14:04:01+09:00",
    "datelastupdated": "2012-12-18T12:05:56+09:00",
    "datepublic": "2010-01-11T00:00:00+09:00"
  }
}
