{
	"vulinfoid": "JVNDB-2016-007923",
	"vulinfodata": {
		"title": "PySAML2 における XML 外部エンティティの脆弱性",
		"vulinfodescription": {
			"overview": "PySAML2 には、XML 外部エンティティ (XXE) の脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "PySAML2 project",
					"productname": "PySAML2",
					"cpe": {
						"text": "cpe:/a:pysaml2_project:pysaml2",
						"version": "2.2"
					}
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "2.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "6.8",
					"vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P"
				},
				{
					"version": "3.0",
					"severity": {
						"text": "Critical",
						"type": "Base"
					},
					"base": "9",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H"
				}
			],
			"impactitem": {
				"description": "ホワイトリストにない第三者により、巧妙に細工された SAML XML リクエストまたは応答を介して、XML 外部エンティティ (XXE) 攻撃を実行される可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "Fix XXE in XML parsing (related to #366) #379",
					"url": "https://github.com/rohe/pysaml2/pull/379"
				},
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "PySAML vulnerable to XXE #366",
					"url": "https://github.com/rohe/pysaml2/issues/366"
				},
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "Fix XXE in XML parsing (related to #366)",
					"url": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b"
				},
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2016-10127",
					"url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-10127"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2016-10127",
					"url": "http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-10127"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-611",
					"url": "https://cwe.mitre.org/data/definitions/611.html",
					"title": "XML 外部エンティティ参照の不適切な制限"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "0",
					"datetime": "2018-02-17T10:37:52+09:00",
					"description": "[2017年03月29日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2017-03-29T17:49:10+09:00",
		"datelastupdated": "2017-03-29T17:49:10+09:00",
		"datepublic": "2016-10-31T00:00:00+09:00"
	}
}
