{
  "vulinfoid": "JVNDB-2020-011774",
  "vulinfodata": {
    "title": "MediaWiki における例外的な状態の処理に関する脆弱性",
    "vulinfodescription": {
      "overview": "MediaWiki には、例外的な状態の処理に関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "MediaWiki",
          "productname": "MediaWiki",
          "cpe": {
            "text": "cpe:/a:mediawiki:mediawiki",
            "version": "2.2"
          },
          "versionnumber": [
            "1.31.10 未満",
            "1.34.4 未満の 1.32.x から 1.34.x"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "5",
          "vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "High",
            "type": "Base"
          },
          "base": "7.5",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
        }
      ],
      "impactitem": {
        "description": "情報を取得される可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "MediaWiki",
          "vulinfoid": "[MediaWiki-l] Security and maintenance release: 1.31.9 / 1.34.3",
          "url": "https://lists.wikimedia.org/pipermail/mediawiki-l/2020-September/048480.html"
        },
        {
          "type": "vendor",
          "name": "MediaWiki",
          "vulinfoid": "[MediaWiki-l] Maintenance release: 1.31.10 / 1.34.4",
          "url": "https://lists.wikimedia.org/pipermail/mediawiki-l/2020-September/048488.html"
        },
        {
          "type": "vendor",
          "name": "Phabricator",
          "vulinfoid": "T260485",
          "url": "https://phabricator.wikimedia.org/T260485"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2020-25869",
          "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25869"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2020-25869",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-25869"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-755",
          "url": "https://cwe.mitre.org/data/definitions/755.html",
          "title": "例外的な状態における不適切な処理"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2021-04-14T16:17:53+09:00",
          "description": "[2021年04月14日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2021-04-14T16:17:53+09:00",
    "datelastupdated": "2021-04-14T16:17:53+09:00",
    "datepublic": "2020-09-24T00:00:00+09:00"
  }
}
