{
	"vulinfoid": "JVNDB-2020-002789",
	"vulinfodata": {
		"title": "Ansible Engine における誤った領域へのリソースの漏えいに関する脆弱性",
		"vulinfodescription": {
			"overview": "Ansible Engine には、誤った領域へのリソースの漏えいに関する脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "レッドハット",
					"productname": "Ansible",
					"cpe": {
						"text": "cpe:/a:redhat:ansible",
						"version": "2.2"
					},
					"versionnumber": [
						"2.7.17 およびそれ以前",
						"2.8.9 およびそれ以前",
						"2.9.6 およびそれ以前"
					]
				},
				{
					"name": "レッドハット",
					"productname": "Ansible Tower",
					"cpe": {
						"text": "cpe:/a:redhat:ansible_tower",
						"version": "2.2"
					}
				},
				{
					"name": "レッドハット",
					"productname": "Red Hat CloudForms Management Engine",
					"cpe": {
						"text": "cpe:/a:redhat:cloudforms_management_engine",
						"version": "2.2"
					}
				},
				{
					"name": "レッドハット",
					"productname": "Red Hat OpenStack",
					"cpe": {
						"text": "cpe:/a:redhat:openstack",
						"version": "2.2"
					}
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "2.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "4.4",
					"vector": "AV:L/AC:M/Au:N/C:P/I:P/A:P"
				},
				{
					"version": "3.0",
					"severity": {
						"text": "High",
						"type": "Base"
					},
					"base": "7",
					"vector": "CVSS:3.0/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H"
				}
			],
			"impactitem": {
				"description": "情報を取得される、情報を改ざんされる、およびサービス運用妨害 (DoS) 状態にされる可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "Insecure creation of temporary directory for become_user #67791",
					"url": "https://github.com/ansible/ansible/issues/67791"
				},
				{
					"type": "vendor",
					"name": "Red Hat Bugzilla",
					"vulinfoid": "Bug 1801735",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1733"
				},
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2020-1733",
					"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-1733"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2020-1733",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-1733"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-668",
					"url": "https://cwe.mitre.org/data/definitions/668.html",
					"title": "誤った領域へのリソースの漏えい"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2020-03-26T09:05:23+09:00",
					"description": "[2020年03月26日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2020-03-26T09:05:23+09:00",
		"datelastupdated": "2020-03-26T09:05:23+09:00",
		"datepublic": "2020-03-03T00:00:00+09:00"
	}
}
