{
  "vulinfoid": "JVNDB-2022-004992",
  "vulinfodata": {
    "title": "Google TensorFlow における例外的な状態のチェックに関する脆弱性",
    "vulinfodescription": {
      "overview": "Google TensorFlow には、例外的な状態のチェックに関する脆弱性が存在します。  "
    },
    "affected": {
      "affecteditem": [
        {
          "name": "Google",
          "productname": "Google TensorFlow",
          "cpe": {
            "text": "cpe:/a:google:tensorflow",
            "version": "2.2"
          }
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "4",
          "vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "6.5",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "impactitem": {
        "description": "サービス運用妨害 (DoS) 状態にされる可能性があります。 "
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。 "
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "GitHub",
          "vulinfoid": "Crash when type cannot be specialized",
          "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-rww7-2gpw-fv6j"
        },
        {
          "type": "vendor",
          "name": "GitHub",
          "vulinfoid": "Properly handle the case where SpecializeType() returns an error `Status`.",
          "url": "https://github.com/tensorflow/tensorflow/commit/cb164786dc891ea11d3a900e90367c339305dc7b"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2022-23572",
          "url": "https://www.cve.org/CVERecord?id=CVE-2022-23572"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2022-23572",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-23572"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-754",
          "url": "https://cwe.mitre.org/data/definitions/754.html",
          "title": "例外的な状態における不適切なチェック"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2023-05-15T12:36:53+09:00",
          "description": "[2023年05月15日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2023-05-15T12:36:53+09:00",
    "datelastupdated": "2023-05-15T12:36:53+09:00",
    "datepublic": "2022-02-03T00:00:00+09:00"
  }
}
