{
	"vulinfoid": "JVNDB-2022-014061",
	"vulinfodata": {
		"title": "Django Software Foundation の Django 他複数ベンダの製品におけるダウンロードしたコードの完全性検証不備に関する脆弱性",
		"vulinfodescription": {
			"overview": "Django Software Foundation の Django 他複数ベンダの製品には、ダウンロードしたコードの完全性検証不備に関する脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "Debian",
					"productname": "Debian GNU/Linux",
					"cpe": {
						"text": "cpe:/o:debian:debian_linux",
						"version": "2.2"
					},
					"versionnumber": [
						"11.0"
					]
				},
				{
					"name": "Django Software Foundation",
					"productname": "Django",
					"cpe": {
						"text": "cpe:/a:djangoproject:django",
						"version": "2.2"
					},
					"versionnumber": [
						"3.2 以上 3.2.15 未満",
						"4.0 以上 4.0.7 未満"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "3.0",
					"severity": {
						"text": "High",
						"type": "Base"
					},
					"base": "8.8",
					"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
				}
			],
			"impactitem": {
				"description": "情報を取得される、情報を改ざんされる、およびサービス運用妨害 (DoS) 状態にされる可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダアドバイザリまたはパッチ情報が公開されています。参考情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2022-36359",
					"url": "https://www.cve.org/CVERecord?id=CVE-2022-36359"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2022-36359",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-36359"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "groups.google.com (8cz--gvaJr4)",
					"url": "https://groups.google.com/g/django-announce/c/8cz--gvaJr4"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "lists.fedoraproject.org (HWY6DQWRVBALV73BPUVBXC3QIYUM24IK)",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK/"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "lists.fedoraproject.org (LTZVAKU5ALQWOKFTPISE257VCVIYGFQI)",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI/"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "security.netapp.com (ntap-20220915-0008)",
					"url": "https://security.netapp.com/advisory/ntap-20220915-0008/"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "www.debian.org (dsa-5254)",
					"url": "https://www.debian.org/security/2022/dsa-5254"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "www.djangoproject.com (security-releases)",
					"url": "https://www.djangoproject.com/weblog/2022/aug/03/security-releases/"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "www.openwall.com (oss-security/2022/08/03/1)",
					"url": "http://www.openwall.com/lists/oss-security/2022/08/03/1"
				},
				{
					"type": "advisory",
					"name": "関連文書",
					"vulinfoid": "docs.djangoproject.com (security)",
					"url": "https://docs.djangoproject.com/en/4.0/releases/security/"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-494",
					"url": "https://cwe.mitre.org/data/definitions/494.html",
					"title": "ダウンロードしたコードの完全性検証不備"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2023-09-14T17:10:50+09:00",
					"description": "[2023年09月14日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2023-09-14T17:10:50+09:00",
		"datelastupdated": "2023-09-14T17:10:50+09:00",
		"datepublic": "2022-08-03T00:00:00+09:00"
	}
}
