{
	"vulinfoid": "JVNDB-2021-014593",
	"vulinfodata": {
		"title": "TensorFlow における整数アンダーフローの脆弱性",
		"vulinfodescription": {
			"overview": "TensorFlow には、整数アンダーフローの脆弱性が存在します。"
		},
		"affected": {
			"affecteditem": [
				{
					"name": "Google",
					"productname": "Google TensorFlow",
					"cpe": {
						"text": "cpe:/a:google:tensorflow",
						"version": "2.2"
					},
					"versionnumber": [
						"2.4.4 未満",
						"2.5.2 未満",
						"2.6.1 未満"
					]
				}
			]
		},
		"impact": {
			"cvss": [
				{
					"version": "2.0",
					"severity": {
						"text": "Low",
						"type": "Base"
					},
					"base": "2.1",
					"vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
				},
				{
					"version": "3.0",
					"severity": {
						"text": "Medium",
						"type": "Base"
					},
					"base": "5.5",
					"vector": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"impactitem": {
				"description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
			}
		},
		"solution": {
			"solutionitem": {
				"description": "ベンダより正式な対策が公開されています。ベンダ情報を参照して適切な対策を実施してください。"
			}
		},
		"related": {
			"relateditem": [
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "Crash in `max_pool3d` when size argument is 0 or negative",
					"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m539-j985-hcr8"
				},
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "Merge pull request #51975 from yongtang:51936-max_pool3d",
					"url": "https://github.com/tensorflow/tensorflow/commit/12b1ff82b3f26ff8de17e58703231d5a02ef1b8b"
				},
				{
					"type": "vendor",
					"name": "GitHub",
					"vulinfoid": "tf.keras.layers.MaxPooling3D crashes #51936",
					"url": "https://github.com/tensorflow/tensorflow/issues/51936"
				},
				{
					"type": "advisory",
					"name": "Common Vulnerabilities and Exposures (CVE)",
					"vulinfoid": "CVE-2021-41196",
					"url": "https://www.cve.org/CVERecord?id=CVE-2021-41196"
				},
				{
					"type": "advisory",
					"name": "National Vulnerability Database (NVD)",
					"vulinfoid": "CVE-2021-41196",
					"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41196"
				},
				{
					"type": "cwe",
					"name": "JVNDB",
					"vulinfoid": "CWE-191",
					"url": "https://cwe.mitre.org/data/definitions/191.html",
					"title": "整数アンダーフロー"
				}
			]
		},
		"history": {
			"historyitem": [
				{
					"historyno": "1",
					"datetime": "2022-10-21T10:27:33+09:00",
					"description": "[2022年10月21日]\\n  掲載"
				}
			]
		},
		"datefirstpublished": "2022-10-21T10:28:06+09:00",
		"datelastupdated": "2022-10-21T10:28:06+09:00",
		"datepublic": "2021-11-05T00:00:00+09:00"
	}
}
