{
  "vulinfoid": "JVNDB-2021-012918",
  "vulinfodata": {
    "title": "IOS用 COVID Certificate App における例外的な状態の処理に関する脆弱性",
    "vulinfodescription": {
      "overview": "IOS用 COVID Certificate App には、例外的な状態の処理に関する脆弱性が存在します。"
    },
    "affected": {
      "affecteditem": [
        {
          "name": "BAG",
          "productname": "COVID Certificate",
          "cpe": {
            "text": "cpe:/a:bag:covid_certificate",
            "version": "2.2"
          },
          "versionnumber": [
            "2.2.0 およびそれ以前"
          ]
        }
      ]
    },
    "impact": {
      "cvss": [
        {
          "version": "2.0",
          "severity": {
            "text": "Low",
            "type": "Base"
          },
          "base": "2.1",
          "vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
        },
        {
          "version": "3.0",
          "severity": {
            "text": "Medium",
            "type": "Base"
          },
          "base": "4.6",
          "vector": "CVSS:3.0/AV:P/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "impactitem": {
        "description": "サービス運用妨害 (DoS) 状態にされる可能性があります。"
      }
    },
    "solution": {
      "solutionitem": {
        "description": "ベンダ情報および参考情報を参照して適切な対策を実施してください。"
      }
    },
    "related": {
      "relateditem": [
        {
          "type": "vendor",
          "name": "BAG",
          "vulinfoid": "Top Page",
          "url": "https://www.bag.admin.ch/bag/de/home.html"
        },
        {
          "type": "advisory",
          "name": "Common Vulnerabilities and Exposures (CVE)",
          "vulinfoid": "CVE-2021-37786",
          "url": "https://www.cve.org/CVERecord?id=CVE-2021-37786"
        },
        {
          "type": "advisory",
          "name": "National Vulnerability Database (NVD)",
          "vulinfoid": "CVE-2021-37786",
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-37786"
        },
        {
          "type": "advisory",
          "name": "関連文書",
          "vulinfoid": "Covid Check QRcode Crash App (dos) #146",
          "url": "https://github.com/admin-ch/CovidCertificate-App-iOS/issues/146"
        },
        {
          "type": "cwe",
          "name": "JVNDB",
          "vulinfoid": "CWE-755",
          "url": "https://cwe.mitre.org/data/definitions/755.html",
          "title": "例外的な状態における不適切な処理"
        }
      ]
    },
    "history": {
      "historyitem": [
        {
          "historyno": "1",
          "datetime": "2022-09-08T15:04:25+09:00",
          "description": "[2022年09月08日]\\n  掲載"
        }
      ]
    },
    "datefirstpublished": "2022-09-08T15:04:25+09:00",
    "datelastupdated": "2022-09-08T15:04:25+09:00",
    "datepublic": "2021-08-16T00:00:00+09:00"
  }
}
